### ISSUE TITLE
Configurable default preferences

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/web#223]
## Feature Suggestion

Originally brought up in the Sensu Slack: It would be nice to be able to configure default preferences for the web application. Primarily this would allow the administration to tailor the initial experience for a new user.

Preferences that could be toggled at present: theme, page size, and dark theme. 

## Possible Implementation

* Configuration would likely need to be cluster wide, so arguably we would want to add a new resource. eg.
  ```yaml
  ---
  type: WebConfiguration
  api_version: core/v2
  metadata:
    name: defaults
  spec:
    motd: |
      I don't remember how Lorum Ipsum goes...
    defaults:
      theme: classic
      dark_mode: true
      rows_per_page: 50
  ```
* Configuration could either be queried during bootstrap or injected into the `index.html` document.

## Context

* https://sensucommunity.slack.com/archives/C9BB9AW7K/p1575489918145300
