### ISSUE TITLE
Dashboard does not honor the trusted-ca-file field when communicating with another Sensu API

### ISSUE THREAD

**Issue by rgeniesse** [sensu/web#228]
## Expected Behavior
When setting the `trusted-ca-file`, documentation in the backend reference says that this attribute will also work with the dashboard to API communication:

> Path to the primary backend CA file. Specifies a fallback SSL/TLS certificate authority in PEM format used for etcd client (mutual TLS) communication if the etcd-trusted-ca-file is not used. This CA file is used in communication between the Sensu dashboard and end user web browsers, as well as communication between sensuctl and the Sensu API.

## Current Behavior
With `trusted-ca-file`, the backend logs an error when attempting to connect from one Sensu backend to another via the API:

> {"component":"apid.routers","errors":[{"message":"Post https://alpha:8080/graphql: x509: certificate signed by unknown authority","locations":[{"line":2,"column":3}],"path":["clusters"]}],"level":"error","msg":"error(s) occurred while executing GraphQL operation","time":"2019-12-12T06:00:55Z"}

## Possible Solution
Have `trusted-ca-file` work dashboard to API communications.

## Steps to Reproduce

1. Create one sensu backend with the following settings (changing paths and URLs as needed):

```
# gateway configuration
etcd-trusted-ca-file: "/tmp/ssl/certs/ca/ca.pem"
etcd-cert-file: "/tmp/ssl/certs/gateway/gateway.pem"
etcd-key-file: "/tmp/ssl/certs/gateway/gateway-key.pem"
etcd-client-cert-auth: true
etcd-advertise-client-urls: https://gateway:2379
etcd-listen-client-urls: https://0.0.0.0:2379

cert-file: "/tmp/ssl/certs/gateway/gateway.pem"
key-file: "/tmp/ssl/certs/gateway/gateway-key.pem"
trusted-ca-file: "/tmp/ssl/certs/ca/ca.pem"
insecure-skip-tls-verify: false
api-url: "https://0.0.0.0:8080"

# jwt configuration
jwt-private-key-file: /tmp/ssl/jwt_key/jwt_private.pem
jwt-public-key-file: /tmp/ssl/jwt_key/jwt_public.pem
```
2. Add some federation settings (changing URLs where needed):
```
---
---
type: User
api_version: core/v2
metadata:
  name: federation-viewer
spec:
  disabled: false
  username: federation-viewer
  password: tester1234
---
type: ClusterRoleBinding
api_version: core/v2
metadata:
  name: federation-viewer-readonly
spec:
  role_ref:
    name: view
    type: ClusterRole
  subjects:
  - name: federation-viewer
    type: User
---
api_version: federation/v1
type: EtcdReplicator
metadata:
  name: AlphaClusterRoleBindings
spec:
  ca_cert: "/tmp/ssl/certs/ca/ca.pem"
  cert: "/tmp/ssl/certs/gateway/gateway.pem"
  key: "/tmp/ssl/certs/gateway/gateway-key.pem"
  url: https://alpha:2379
  api_version: core/v2
  resource: ClusterRoleBinding
  replication_interval_seconds: 30
---
api_version: federation/v1
type: Cluster
metadata:
  name: alpha
spec:
  api_urls:
  - https://alpha:8080
```
3. Log in as the newly created `federation-viewer` user. 
4. Attempt to view the other sensu backend in the upper left coner.
5. Observe error in backend logs mentioned above, as well as UI error.

## Context
This might impact more areas, but for now I've only noticed it when setting up Federation. I also have a docker environment I can share if needed for easily showing the issue.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): All 5.15.0
* Installation method (packages, binaries, docker etc.): docker image, latest 5.15.0.
* Operating System and version (e.g. Ubuntu 14.04): Apline
* Browser used: tried Firefox and Chrome.
