### ISSUE TITLE
Session expire

### ISSUE THREAD

**Issue by Ashwitha01** [sensu/web#329]
While running **sensu application** through helm chart, the **"session expire"** and **sign in** again issue is hitting for every 15 seconds.
If I keep service IP as LoadBalancer, then only Issue is shown up, but not for Cluster-IP.
And I have used **sensu/sensu** docker image. 
Is the problem with with my code or docker image?
It would be great if anyone help me out to solve it.

**Comment by portertech** [comment]
Sessions are not sticky, should be able to switch between Web UI instances on backends in the same cluster. Have you clustered your backends correctly?

**Comment by Ashwitha01** [comment]
@portertech thank you for the reply. I ran the application through helm chart, where I kept official image of sensu
![Screenshot from 2020-07-17 10-29-23](https://user-images.githubusercontent.com/48426787/87750640-a1a67600-c819-11ea-8831-3c8d9814ec98.png)
and If I keep services as **ClusterIP** , It is not throwing session expire error.
![Screenshot from 2020-07-17 10-29-33](https://user-images.githubusercontent.com/48426787/87750693-c4d12580-c819-11ea-977d-a7e15d882293.png)
but If Service IP: **LoadBalancer** then it throws session expire error.
All the pods and services are up and running.
In the cluster backend I have configured the services necessary to run the application. 
What I'm missing here? Can you help me to solve?

**Comment by pschmitt** [comment]
I've encountered the same issue and managed to solve it by adding the following annotations to the ingress definition:
```yaml

nginx.ingress.kubernetes.io/affinity: "cookie"
nginx.ingress.kubernetes.io/session-cookie-name: "route"
nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
```

Ref: https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/

**Comment by Ashwitha01** [comment]
thank you @pschmitt , it works but only for 10 to 15 minutes it will stay , earlier I could not even login to dashboard.
What should I do to stay on the dashboard for longer time?
here is my ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sensu-dashboard
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/force-ssl-redirect:      "false"
spec:
{{- if .Values.ingress.dashboard.tls }}
  tls:
  {{- range .Values.ingress.dashboard.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.dashboard.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: "{{ $fullName }}-dashboard"
              servicePort: 3000
  {{- end }} 
```

at Values.yaml I mentioned it as
```
ingress:
   dashboard:
   enabled: true
   path: /
   hosts:
     - sensu-dashboard
   tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
```
It would be great if you help me to solve.
