### ISSUE TITLE
Problem Implementing OIDC with OKTA Part 2

### ISSUE THREAD

**Issue by bradpoulton** [sensu/web#334]
I am attempting to setup Sensu dashboard with OKTA OIDC auth. After setting up sensu for OKTA auth, i got this error.

Expected Behavior
No stack trace when logging into Sensu with OIDC auth method (OKTA).

Current Behavior
Got a stack trace.

Steps to Reproduce (for bugs)
Setup OKTA OIDC auth following steps here: https://docs.sensu.io/sensu-go/latest/installation/auth/#okta

Sensu config:
```
type: oidc
api_version: authentication/v2
metadata:
  name: oidc_okta
spec:
  additional_scopes:
  - groups
  - email
  client_id: client_id
  client_secret: client_secret
  redirect_uri: https://sensu.mydomain.local:8080/api/enterprise/authentication/v2/oidc/callback
  server: https://myokta.okta.com
  groups_claim: groups
  groups_prefix: 'okta:'
  username_claim: email
  username_prefix: 'okta:'
```

Context
Encountered during setting up OKTA OIDC auth.

Browser Stack Trace:
```
Error: GraphQL error: no claims found in the request context
    at new ApolloError (https://sensu.mydomain.local:8000/static/js/app_9361.js:2:124730)
    at https://sensu.mydomain.local:8000/static/js/app_9361.js:2:147991
    at https://sensu.mydomain.local:8000/static/js/app_9361.js:2:154452
    at Set.forEach (<anonymous>)
    at https://sensu.mydomain.local:8000/static/js/app_9361.js:2:154428
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (https://sensu.mydomain.local:8000/static/js/app_9361.js:2:154378)
    at https://sensu.mydomain.local:8000/static/js/app_9361.js:2:156493
    at Object.next (https://sensu.mydomain.local:8000/static/js/app_9361.js:2:2241392)
    at notifySubscription (https://sensu.mydomain.local:8000/static/js/app_9361.js:2:2238670)
```

Your Environment
Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-backend/sensu web
sensu/web revision: 5.21.0
sensu-backend version 5.21.0+ee, enterprise edition, build 081a854d483d7881bbcf4cb60c44f87ea5fdf425, built 2020-06-11T19:45:19Z, built with go1.13.7
web revision b6d7442
Installation method (packages, binaries, docker etc.): rpm packages
Operating System and version (e.g. Ubuntu 14.04): redhat 7.8
web is running on port 8000 (not using default port)
API is running on port 8080

I have a cluster-role-binding 
```
type: ClusterRoleBinding
api_version: core/v2
metadata:
  created_by: admin
  labels:
    sensu.io/managed_by: sensuctl
  name: ldap-my-admin
spec:
  role_ref:
    name: my-admin
    type: ClusterRole
  subjects:
  - name: ldap:my-admins
    type: Group
  - name: okta:my-admins
    type: Group
```

/var/log/messages entry
```
Aug  4 23:17:07 sensu sensu-backend: {"component":"apid.routers","errors":[{"message":"no claims found in the request context","locations":[{"line":2,"column":3}],"path":["resp"]}],"level":"error","msg":"error(s) occurred while executing GraphQL operation","time":"2020-08-04T23:17:07Z"}
```

I am able to decrypt and view the JWT and I see okta:my-admins group in the JWT.
